# Generated by Django 6.0.6 on 2026-07-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('cellars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouteille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millesime', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour un vin non millésimé.', null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('A_GARDER', 'À garder'), ('A_BOIRE', 'À boire'), ('DEPASSE', 'Dépassé')], default='A_GARDER', max_length=10)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('apogee_debut', models.PositiveIntegerField(blank=True, help_text="Année de début de la fenêtre d'apogée.", null=True)),
                ('apogee_fin', models.PositiveIntegerField(blank=True, help_text="Année de fin de la fenêtre d'apogée.", null=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('cuvee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouteilles', to='catalog.cuvee')),
                ('emplacement', models.ForeignKey(blank=True, help_text="Laisser vide si le placement physique n'a pas encore été fait.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouteilles', to='cellars.emplacement')),
            ],
            options={
                'verbose_name': 'Bouteille (stock)',
                'verbose_name_plural': 'Bouteilles (stock)',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('CONSOMMATION', 'Consommation'), ('AJUSTEMENT', "Ajustement d'inventaire")], max_length=15)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('occasion', models.CharField(blank=True, help_text='Ex: Anniversaire, dîner avec X', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('bouteille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventory.bouteille')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
