# Generated by Django 6.0.6 on 2026-07-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cellars", "0002_emplacement_disposition_emplacement_nb_colonnes_and_more"),
        ("inventory", "0003_notedegustation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rangement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case",
                    models.PositiveIntegerField(
                        help_text="Index 0-based de la case dans la grille (ligne × nb_colonnes + colonne)."
                    ),
                ),
                (
                    "bouteille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rangements",
                        to="inventory.bouteille",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rangements",
                        to="cellars.emplacement",
                    ),
                ),
            ],
            options={
                "ordering": ["emplacement_id", "case"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("emplacement", "case"),
                        name="rangement_case_unique_par_emplacement",
                    )
                ],
            },
        ),
    ]
