# Generated by Django 6.0.6 on 2026-07-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_cuvee_prix_marchands_and_more"),
        ("inventory", "0004_rangement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notedegustation",
            name="cuvee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="degustations",
                to="catalog.cuvee",
            ),
        ),
    ]
