# Generated by Django 6.0.6 on 2026-07-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_notedegustation_cuvee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bouteille",
            name="statut",
        ),
    ]
