# Generated by Django 6.0.6 on 2026-07-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('site_web', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'region'), name='unique_domaine_par_region')],
            },
        ),
        migrations.CreateModel(
            name='Cuvee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('appellation', models.CharField(blank=True, max_length=255)),
                ('couleur', models.CharField(choices=[('ROUGE', 'Rouge'), ('BLANC', 'Blanc'), ('ROSE', 'Rosé'), ('BULLES', 'Bulles'), ('AUTRE', 'Autre')], max_length=10)),
                ('code_barres', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reference_externe_id', models.CharField(blank=True, help_text='Identifiant dans une base de référence externe (ex: Wine-Searcher, Vivino).', max_length=128)),
                ('cepages', models.ManyToManyField(blank=True, related_name='cuvees', to='catalog.cepage')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuvees', to='catalog.domaine')),
            ],
            options={
                'ordering': ['domaine__nom', 'nom'],
            },
        ),
    ]
