# Generated by Django 6.0.6 on 2026-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_cuvee_historique_prix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuvee",
            name="prix_marchands",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Prix marchands wineapi [{marchand, prix, devise, url, releve_le}].",
            ),
        ),
        migrations.AlterField(
            model_name="cuvee",
            name="reference_externe_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant dans une base de référence externe (ex: wineapi.io).",
                max_length=128,
            ),
        ),
    ]
