# Generated by Django 6.0.6 on 2026-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_cuvee_prix_marchands_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceLwin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lwin",
                    models.CharField(
                        help_text="Code LWIN7 Liv-ex.", max_length=16, unique=True
                    ),
                ),
                ("producteur", models.CharField(max_length=255)),
                ("vin", models.CharField(blank=True, default="", max_length=255)),
                ("pays", models.CharField(blank=True, default="", max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=255)),
                (
                    "sous_region",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "couleur",
                    models.CharField(
                        choices=[
                            ("ROUGE", "Rouge"),
                            ("BLANC", "Blanc"),
                            ("ROSE", "Rosé"),
                            ("BULLES", "Bulles"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                    ),
                ),
                (
                    "classification",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "référence LWIN",
                "verbose_name_plural": "références LWIN",
                "ordering": ["producteur", "vin"],
            },
        ),
    ]
