# Generated by Django 6.0.6 on 2026-07-13 14:02
"""Verrouille l'identité canonique du référentiel (Phase 0 de la revue).

D'abord on dédoublonne les données existantes — producteurs scindés par le
défaut ``get_or_create(region="")`` et cuvées en double sur une même clé forte
(code-barres / référence externe) — puis on pose les contraintes d'unicité qui
empêchent la ré-accumulation de doublons. Voir docs/architecture-referentiel.md
(diagnostic D3, Phase 0).
"""

from collections import defaultdict

from django.db import migrations, models


def dedup_domaines(apps, schema_editor):
    """Fusionne les fiches producteur scindées par l'ancien ingest.

    Le nom est l'identité d'un producteur. Quand plusieurs fiches partagent un
    nom avec *exactement une* variante renseignée en région, les fiches sans
    région (artefact de l'enrichissement) y sont rattachées : leurs cuvées sont
    re-pointées puis les doublons vides sont supprimés. Les cas ambigus (aucune
    ou plusieurs régions distinctes) sont laissés intacts par prudence.
    """
    Domaine = apps.get_model("catalog", "Domaine")
    Cuvee = apps.get_model("catalog", "Cuvee")

    par_nom = defaultdict(list)
    for domaine in Domaine.objects.all().order_by("pk"):
        par_nom[domaine.nom].append(domaine)

    for doublons in par_nom.values():
        if len(doublons) < 2:
            continue
        avec_region = [d for d in doublons if d.region]
        if len(avec_region) != 1:
            continue  # ambigu : on ne fusionne pas automatiquement
        cible = avec_region[0]
        for domaine in doublons:
            if domaine.pk == cible.pk or domaine.region:
                continue
            Cuvee.objects.filter(domaine=domaine).update(domaine=cible)
            domaine.delete()


def dedup_cuvees(apps, schema_editor):
    """Fusionne les cuvées en double sur une clé d'identité forte.

    Pour chaque valeur non vide de code-barres puis de référence externe, la plus
    ancienne cuvée (plus petit pk) est conservée ; le stock privé (bouteilles) et
    les notes de dégustation des doublons y sont re-pointés avant suppression, ce
    qui préserve les données privées (FK en PROTECT).
    """
    Cuvee = apps.get_model("catalog", "Cuvee")
    Bouteille = apps.get_model("inventory", "Bouteille")
    NoteDegustation = apps.get_model("inventory", "NoteDegustation")

    for champ in ("code_barres", "reference_externe_id"):
        groupes = defaultdict(list)
        for cuvee in Cuvee.objects.exclude(**{champ: ""}).order_by("pk"):
            groupes[getattr(cuvee, champ)].append(cuvee)
        for cuvees in groupes.values():
            if len(cuvees) < 2:
                continue
            cible, *surplus = cuvees
            for doublon in surplus:
                Bouteille.objects.filter(cuvee=doublon).update(cuvee=cible)
                NoteDegustation.objects.filter(cuvee=doublon).update(cuvee=cible)
                doublon.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_referencelwin"),
        # Le dédoublonnage re-pointe des Bouteille / NoteDegustation privées.
        ("inventory", "0005_alter_notedegustation_cuvee"),
    ]

    operations = [
        migrations.RunPython(dedup_domaines, migrations.RunPython.noop),
        migrations.RunPython(dedup_cuvees, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cuvee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code_barres", ""), _negated=True),
                fields=("code_barres",),
                name="unique_cuvee_code_barres",
            ),
        ),
        migrations.AddConstraint(
            model_name="cuvee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_externe_id", ""), _negated=True),
                fields=("reference_externe_id",),
                name="unique_cuvee_reference_externe",
            ),
        ),
    ]
