# Generated by Django 6.0.6 on 2026-07-13 16:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_dedup_identite_cuvee"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        db_index=True,
                        help_text="Canal source (ex: wineapi, claude, lwin, openfoodfacts, scrape:...).",
                        max_length=64,
                    ),
                ),
                ("releve_le", models.DateTimeField(auto_now_add=True)),
                (
                    "confiance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Confiance a priori dans ce relevé (0 à 1), défaut par canal.",
                        max_digits=3,
                    ),
                ),
                (
                    "payload_brut",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Réponse brute du canal, telle quelle.",
                    ),
                ),
                (
                    "champs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Champs normalisés affirmés par ce relevé.",
                    ),
                ),
                (
                    "cuvee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="catalog.cuvee",
                    ),
                ),
            ],
            options={
                "verbose_name": "observation de source",
                "verbose_name_plural": "observations de source",
                "ordering": ["-releve_le"],
                "indexes": [
                    models.Index(
                        fields=["cuvee", "canal"], name="catalog_sou_cuvee_i_308822_idx"
                    )
                ],
            },
        ),
    ]
