# Generated by Django 6.0.6 on 2026-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_sourceobservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuvee",
            name="provenance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provenance par champ {champ: {canal, date, confiance}}.",
            ),
        ),
    ]
