# Generated by Django 6.0.6 on 2026-07-13 16:44
"""Fait du code LWIN une identité de vin canonique (Phase 3 / D4).

On dédoublonne d'abord les cuvées partageant un même code LWIN (en re-pointant le
stock privé et les notes de dégustation), puis on pose la contrainte d'unicité
partielle. Voir docs/architecture-referentiel.md (Phase 3).
"""

from collections import defaultdict

from django.db import migrations, models


def dedup_cuvees_par_lwin(apps, schema_editor):
    """Fusionne les cuvées en double sur un même code LWIN non vide.

    La plus ancienne (plus petit pk) est conservée ; bouteilles et notes de
    dégustation des doublons y sont re-pointées avant suppression (FK PROTECT,
    données privées préservées).
    """
    Cuvee = apps.get_model("catalog", "Cuvee")
    Bouteille = apps.get_model("inventory", "Bouteille")
    NoteDegustation = apps.get_model("inventory", "NoteDegustation")

    groupes = defaultdict(list)
    for cuvee in Cuvee.objects.exclude(lwin_code="").order_by("pk"):
        groupes[cuvee.lwin_code].append(cuvee)
    for cuvees in groupes.values():
        if len(cuvees) < 2:
            continue
        cible, *surplus = cuvees
        for doublon in surplus:
            Bouteille.objects.filter(cuvee=doublon).update(cuvee=cible)
            NoteDegustation.objects.filter(cuvee=doublon).update(cuvee=cible)
            doublon.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_cuvee_provenance"),
        # Le dédoublonnage re-pointe des Bouteille / NoteDegustation privées.
        ("inventory", "0005_alter_notedegustation_cuvee"),
    ]

    operations = [
        migrations.RunPython(dedup_cuvees_par_lwin, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cuvee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lwin_code", ""), _negated=True),
                fields=("lwin_code",),
                name="unique_cuvee_lwin_code",
            ),
        ),
    ]
