# Generated by Django 6.0.6 on 2026-07-13 16:59

import django.core.validators
from django.db import migrations, models

from apps.catalog.apogee import MILLESIMES


def seed_millesimes(apps, schema_editor):
    """Sème la table depuis la référence intégrée ``apogee.MILLESIMES``.

    ``apogee.MILLESIMES`` demeure le repli hors-ligne ; la base devient la source
    de vérité, désormais corrigeable/enrichissable sans redéploiement."""
    MillesimeReference = apps.get_model("catalog", "MillesimeReference")
    lignes = [
        MillesimeReference(region_cle=region, annee=annee, note=note, source="seed")
        for region, annees in MILLESIMES.items()
        for annee, note in annees.items()
    ]
    MillesimeReference.objects.bulk_create(lignes, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_cuvee_unique_lwin_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="MillesimeReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_cle",
                    models.CharField(
                        help_text="Grande région viticole normalisée (ex: bordeaux, bourgogne).",
                        max_length=32,
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                (
                    "note",
                    models.PositiveSmallIntegerField(
                        help_text="Qualité du millésime, de 1 (faible) à 5 (exceptionnel).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="seed",
                        help_text="Origine de la note (ex: seed, manuel, claude, scrape:...).",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "référence millésime",
                "verbose_name_plural": "références millésimes",
                "ordering": ["region_cle", "annee"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region_cle", "annee"),
                        name="unique_millesime_par_region",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_millesimes, migrations.RunPython.noop),
    ]
