# Generated by Django 6.0.6 on 2026-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_millesime_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(
                        help_text="Nom du paramètre (ex: WINEAPI_KEY).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("valeur", models.TextField(blank=True, default="")),
                ("maj_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "paramètre",
                "verbose_name_plural": "paramètres",
                "ordering": ["cle"],
            },
        ),
    ]
