# Generated by Django 6.0.6 on 2026-07-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_parametre"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppelSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Nom du fournisseur (ex: grapeminds).", max_length=32
                    ),
                ),
                (
                    "mois",
                    models.CharField(help_text="Période « YYYY-MM ».", max_length=7),
                ),
                ("nombre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "appel de source",
                "verbose_name_plural": "appels de source",
                "ordering": ["-mois", "source"],
                "unique_together": {("source", "mois")},
            },
        ),
    ]
