# Generated by Django 6.0.6 on 2026-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_appelsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuvee",
            name="photo_etiquette",
            field=models.ImageField(
                blank=True,
                help_text="Vignette d'étiquette issue d'un scan, recadrée sur le texte.",
                null=True,
                upload_to="etiquettes/%Y/%m/",
            ),
        ),
    ]
