# Generated by Django 6.0.6 on 2026-07-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_dedup_nom_cuvee"),
    ]

    operations = [
        migrations.CreateModel(
            name="TacheImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_import",
                    models.CharField(
                        choices=[("CATALOGUE", "Catalogue transportable")],
                        default="CATALOGUE",
                        max_length=16,
                    ),
                ),
                (
                    "nom_fichier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("ECHEC", "Échec"),
                        ],
                        default="EN_COURS",
                        max_length=10,
                    ),
                ),
                (
                    "avancement",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Compte rendu partiel {cuvees_lues, creees, ...}.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, default="", help_text="Message d'erreur éventuel."
                    ),
                ),
                ("demarree_le", models.DateTimeField(auto_now_add=True)),
                ("terminee_le", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "tâche d'import",
                "verbose_name_plural": "tâches d'import",
                "ordering": ["-demarree_le"],
            },
        ),
    ]
