# Generated by Django 6.0.6 on 2026-07-06 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Armoire 1, Clayette 3, B4', max_length=255)),
                ('type_emplacement', models.CharField(choices=[('ARMOIRE', 'Armoire'), ('CASIER', 'Casier'), ('CLAYETTE', 'Clayette'), ('CAISSE', 'Caisse bois'), ('CASE', 'Case individuelle')], max_length=10)),
                ('capacite', models.PositiveIntegerField(blank=True, help_text='Nombre de bouteilles que ce noeud peut contenir.', null=True)),
                ('ligne', models.PositiveIntegerField(blank=True, help_text="Position en ligne pour l'affichage en grille.", null=True)),
                ('colonne', models.PositiveIntegerField(blank=True, help_text="Position en colonne pour l'affichage en grille.", null=True)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='cellars.cave')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='cellars.emplacement')),
            ],
            options={
                'ordering': ['cave', 'parent_id', 'ligne', 'colonne', 'nom'],
            },
        ),
    ]
