# Generated by Django 6.0.6 on 2026-07-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cellars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emplacement",
            name="disposition",
            field=models.CharField(
                choices=[
                    ("ALIGNE", "Aligné"),
                    ("DECALE_GAUCHE", "Décalé à gauche"),
                    ("DECALE_DROITE", "Décalé à droite"),
                ],
                default="ALIGNE",
                help_text="Empilement des bouteilles d'une rangée à l'autre.",
                max_length=13,
            ),
        ),
        migrations.AddField(
            model_name="emplacement",
            name="nb_colonnes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Bouteilles par rangée (largeur).", null=True
            ),
        ),
        migrations.AddField(
            model_name="emplacement",
            name="nb_rangees",
            field=models.PositiveIntegerField(
                blank=True, help_text="Nombre de rangées empilées (hauteur).", null=True
            ),
        ),
    ]
